export const ADD_TODO = "ADD_TOTO";

export const TRY_AUTH = "TRY_AUTH";

export const TRY_AUTH_ERROR = "TRY_AUTH_ERROR";

export const TRY_AUTH_SUCCESS = "TRY_AUTH_SUCCESS";

export const AUTH = "AUTH";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const ADD_QUESTION = "ADD_QUESTION";

export const DELETE_QUESTION = "DELETE_QUESTION";

export const EDIT_QUESTION = "EDIT_QUESTION";

export const ADD_TEST = "ADD_TEST";

export const ADD_TEST_SUCCESS_MSG = "ADD_TEST_SUCCESS_MSG";

export const ADD_TEST_ERROR_MSG = "ADD_TEST_ERROR_MSG";

export const CLEAR_TESTS = "CLEAR_TESTS";

export const ADD_CREATED_TESTS = "ADD_CREATED_TESTS";

export const ADD_AVAILABLE_TESTS = "ADD_AVAILABLE_TESTS";

export const SET_NEW_AVAILABLE_TEST = "SET_NEW_AVAILABLE_TEST";

export const SET_BEST_AVAILABLE_TEST = "SET_BEST_AVAILABLE_TEST";

export const SET_POPULAR_AVAILABLE_TEST = "SET_POPULAR_AVAILABLE_TEST";

export const ADD_CANDIDATE = "ADD_CANDIDATE";

export const ADD_CANDIDATE_SUCCESS_MSG = "ADD_CANDIDATE_SUCCESS_MSG";

export const ADD_CANDIDATE_ERROR_MSG = "ADD_CANDIDATE_ERROR_MSG";

export const DELETE_CANDIDATE = "DELETE_CANDIDATE";

export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";

export const INVITE_CANDIDATE = "INVITE_CANDIDATE";

export const INVITE_CANDIDATE_ERROR_MSG = "INVITE_CANDIDATE_ERROR_MSG";
